### ISSUE TITLE
Hiding relatives who are not related to the basic person

### ISSUE THREAD

**Issue by Jacute** [gramps-project/gramps-web#779]
**Is your feature request related to a problem? Please describe.**
The relationship graph displays absolutely everyone, including those who are not related to me in any way. Example: I have a brother who is married, but I do not want to see his wife on the graph because she is not related to me, but I do want to see his children because they are my nephews.

**Describe the solution you'd like**
A button that will hide relatives who are not related to the base person

**Comment by Jacute** [comment]
https://github.com/gramps-project/gramps-web/discussions/711

**Comment by DavidMStraub** [comment]
Clarification: you are referring to relationship by consanguinity. You're brother's wife is your sister in law, so she *is* related to you, but only by affinity, not consanguinity. So the request is to remove non-consangineous relationships.

**Comment by DavidMStraub** [comment]
>  A button that will hide relatives who are not related to the base person

I don't think a button makes sense - this seems to me a setting just like the already existing ones (N generations etc.)

**Comment by DavidMStraub** [comment]
Note that this would also hide the center person's spouse(s).

**Comment by Jacute** [comment]
Yes, that's right. I only want to see relationship by consanguinity. It can be setting like N generations

**Comment by ConteDeStGermain** [comment]
As FYI I already implemented this under the currently closed pr https://github.com/gramps-project/gramps-web/pull/1342

**Comment by DavidMStraub** [comment]
Well - you implemented a new view. This issue discussion (that you missed) argued for making it a setting under the relationship graph. Do you have a counterargument?

**Comment by ConteDeStGermain** [comment]
> Well - you implemented a new view. This issue discussion (that you missed) argued for making it a setting under the relationship graph. Do you have a counterargument?

I can set this view to be my default view when I click on family tree in my user settings. This let's me easily see my blood relatives and add them which is especially useful when starting out and doing work in parallel.

**Comment by DavidMStraub** [comment]
The setting could be persisted too. I don't see why we should use the precious real estate in the tree type bar for a view that is just marginally different from another one. Unless I am missing something.

**Comment by DavidMStraub** [comment]
(We already persist settings like number of generations.)

**Comment by ConteDeStGermain** [comment]
I guess the only argument I could say is that besides "better UX" having a checkbox (or similar) under the relationship graph just makes that settings box more convoluted. What do you think?

**Comment by DavidMStraub** [comment]
The settings dialog currently has three options: max degrees of separation, max number of images displayed and name format. I don't think adding a fourth one would hurt.

**Comment by ConteDeStGermain** [comment]
Alright, I can change it to have it in the current dialog. Also, I had also added the option to show or hide spouses. (let's say if for some reason I'd want to hide/show my cousin's wife or my great grand aunt's husband etc who aren't related to me by blood). I'd like to keep that option in. What do you think?
